name: Pull Request

on:

  pull_request:
    branches:
      - main

jobs:

  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@v2.0.0

  docker_build:
    uses: "philipcristiano/workflows/.github/workflows/docker-build.yml@main"
    with:
      timeout: 25

  rust:
    uses: "philipcristiano/workflows/.github/workflows/rust.yml@main"
    with:
      setup_script: |
          curl -sL https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.1/tailwindcss-linux-x64 -o tailwindcss
          chmod +x tailwindcss
          mv tailwindcss /usr/local/bin

  flake:
    uses: "philipcristiano/workflows/.github/workflows/nix.yml@main"
    with:
      flakes-from-devshell: true
      script: |
        unset DATABASE_URL
        cargo build
