name: Main Branch Deploy

on:
  push:
    branches:
      - main

jobs:

  flake:
    runs-on: nixos-latest
    steps:
      - name: Install Node
        run: nix-env -i nodejs
      - uses: actions/checkout@v4
      - name: Build
        env:
          SQLX_OFFLINE: true
        run: nix --experimental-features 'nix-command flakes' develop --command cargo build
